#!/bin/bash
# WF 2017-06-05
# https://stackoverflow.com/questions/16976214/gradle-build-only-one-module
../gradlew :can4eve:fatjar
jar="./build/libs/can4eve-all-0.0.1.jar"
java -jar $jar  -f -d -dv cu.usbserial-113010822821 -lf logfile.txt
