# this is a java project using maven
# it also compiles an android result with gradle
# see https://github.com/travis-ci/travis-ci/issues/2551
language: android 
#language: java
# 
# Java 8
#  
# to avoid Unsupported major.minor version 52.0 we need to specify the JDK to be used
# https://stackoverflow.com/a/40208648/1497139
jdk: oraclejdk8
# support for headless Swing tests and other gui stuff
# https://docs.travis-ci.com/user/gui-and-headless-browsers/ 
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# switch off gpg handling
install: mvn install -DskipTests=true -Dgpg.skip=true
script: mvn test
# Android 
# https://docs.travis-ci.com/user/languages/android/
android:
  components:
    - tools
    - build-tools-25.0.3
    - android-25

# Caching
# see https://stackoverflow.com/questions/40295515/caching-android-sdk-in-travis-ci
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-3
    - $HOME/.gradle/caches/3.5
# Java FX support
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
