#!/bin/bash
# WF 2017-07-06
#https://stackoverflow.com/a/1638397/1497139
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH
java -jar obdii/target/com.bitplan.obdii-0.0.1-jar-with-dependencies.jar
